version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_cashing: false 

      - run: mvn clean install

      - run: 
          name: Build Docker Image
          command: docker build -t registry.heroku.com/$HEROKU_APP_NAME/ web . 

