version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer 
          
      - run: mvn clean install
  