version: 2.1

orbs:
  heroku: circleci/heroku@0.0.8

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    
    working_directory: ~/repo

    steps:
      - checkout
      - heroku/install
      - setup_remote_docker:
          docker_layer_cashing: false 

      - run: mvn clean install

      - run: 
          name: Build Docker Image
          command: docker build -t registry.heroku.com/$HEROKU_APP_NAME/web .

      - run:
         name: Login To Heroku CR
         command: docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com

      - run:
         name: Push to Heroku CR
         command: docker push registry.heroku.com/$HEROKU_APP_NAME/web:latest
      
      - run:
         name: Publish image
         command: heroku container:release web -a $HEROKU_APP_NAME

